config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root :to => "pages#index", :via => [:get, :post]

  resources :items
  resources :inventory_items
  resources :inventory_transactions
end

app/models/inventory_item.rb
class InventoryItem < ActiveRecord::Base
  # item_id as a foriegn key to items
  belongs_to :item

  has_many :inventory_transactions

  validates :quantity, :presence => true, :numericality => true

  def to_s
    self.item.name
  end

  def total
    self.item.price * self.quantity
  end
end

app/models/inventory_transaction.rb
class InventoryTransaction < ActiveRecord::Base
  TRANSACTION_TYPES = ["in", "out"]

  belongs_to :inventory_item

  validates :quantity, :presence => true, :numericality => true
  validates :transacted_at, :presence => true
  validates :transaction_type, :presence => true, :inclusion => { :in => TRANSACTION_TYPES }

def to_x
     self.inventory_item.to_s
end
  validate :cannot_be_greater_than_or_equal_to_current_inventory_quantity

  def cannot_be_greater_than_or_equal_to_current_inventory_quantity
    if self.quantity > self.inventory_item.quantity and self.transaction_type == "out"
      errors.add(:quantity, "Transaction quantity exceeds the availble stock")
    end
  end

  validate :transacted_at_cannot_be_less_than_current_date

  def transacted_at_cannot_be_less_than_current_date
    if self.transacted_at < Time.now
      errors.add(:transacted_at, "Cannot be less than current date")
    end
  end
end

app/models/item.rb
class Item < ActiveRecord::Base
  validates :name, :presence => true, :uniqueness => true
  validates :code, :presence => true, :uniqueness => true

  has_many :inventory_items

  def to_s
    self.code
  end

  def to_x
    self.price
  end
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  before_action :authenticate_user!
  protect_from_forgery with: :exception
end

app/controllers/inventory_items_controller.rb
class InventoryItemsController < ApplicationController

   def index
   @inventory_items = InventoryItem.all

    render :template => "inventory_items/index"
  end

  def show
    @inventory_item = InventoryItem.all

    render :template => "inventory_items/index"
  end

  def show
    @inventory_item = InventoryItem.find(params[:id])

    render :template => "inventory_items/show.html.erb"
  end

  def new
    @inventory_item = InventoryItem.new

    render :template => "inventory_items/new"
  end

  def create
    @inventory_item = InventoryItem.new(inventory_item_params)

    if @inventory_item.save
      redirect_to inventory_items_path
    else
      render :template => "inventory_items/new"
    end
  end

  def edit
    @inventory_item = InventoryItem.find(params[:id])

    render :template => "inventory_items/edit"
  end

  def update
    @inventory_item = InventoryItem.find(params[:id])

    if @inventory_item.update(inventory_item_params)
      redirect_to inventory_items_path
    else
      render :template => "inventory_items/edit"
    end
  end

  def destroy
    InventoryItem.find(params[:id]).destroy!
    redirect_to inventory_items_path
  end
  
  def inventory_item_params
    params.require(:inventory_item).permit!
  end
end

app/controllers/inventory_transactions_controller.rb
class InventoryTransactionsController < ApplicationController

  def index
    @inventory_transactions = InventoryTransaction.all

    render :template => "inventory_transactions/index"
  end

  def new
    @inventory_transaction = InventoryTransaction.new

    render :template => "inventory_transactions/new"
  end

  def create
    @inventory_transaction = InventoryTransaction.new(inventory_transaction_params)

    # After saving, update the attached inventory_item's quantity
    if @inventory_transaction.save
      quantity = @inventory_transaction.quantity
      transaction_type = @inventory_transaction.transaction_type

      if transaction_type == "in"
        new_quantity = @inventory_transaction.inventory_item.quantity + quantity
        @inventory_transaction.inventory_item.update(:quantity => new_quantity)
      elsif transaction_type == "out"
        new_quantity = @inventory_transaction.inventory_item.quantity - quantity
        @inventory_transaction.inventory_item.update(:quantity => new_quantity)
      end

      redirect_to inventory_items_path
    else
      render :template => "inventory_transactions/new"
    end
  end

  def inventory_transaction_params
    params.require(:inventory_transaction).permit!
  end
end

app/controllers/items_controller.rb
class ItemsController < ApplicationController

  def index
    @items = Item.all

    render :template => "items/index"
  end

  def show
    @item = Item.find(params[:id])

    render :template => "items/show.html.erb"
  end

  def new
    @item = Item.new

    render :template => "items/new"
  end

  def create
    @item = Item.new(item_params)

    if @item.save
      redirect_to items_path
    else
      render :template => "items/new"
    end
  end

  def edit
    @item = Item.find(params[:id])

    render :template => "items/edit"
  end

  def update
    @item = Item.find(params[:id])

    if @item.update(item_params)
      redirect_to items_path
    else
      render :template => "items/edit"
    end
  end

  def destroy
    Item.find(params[:id]).destroy!
    redirect_to items_path
  end
  
  def item_params
    params.require(:item).permit!
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
	# Returns the full title on a per-page basis.
	def full_title(page_title)
		base_title = "The Shopping Carrot"
		if page_title.empty?
		base_title
		else
		"#{base_title} | #{page_title}"
		end
	end
end

app/views/inventory_items/edit.html.erb
<% provide(:title, 'Edit Inventory Item') %>
<h1>Edit Inventory Item</h1>

<%= simple_form_for(@inventory_item) do |f| %>
  <%= f.association :item %>
  <% if @inventory_item.new_record? %>
    <%= f.input :quantity %>
  <% end %>
  <hr>
  <%= f.submit "Save Record" %>
<% end %>

<%= link_to "Back to inventory_items", inventory_items_path %>

app/views/inventory_items/index.html.erb
<% provide(:title, 'Item Shop') %>
<h1>Item Shop</h1>

<%= link_to "Item Supplier", items_path %>
<%= link_to "Add Item To Shop", new_inventory_item_path %>
<%= link_to "Check Out Cart", new_inventory_transaction_path %>
<!-- admins should only see transaction history -->
<%= link_to "Transaction History", inventory_transactions_path %>

<table width="100%">
  <tr>
    <th>Item</th>
    <th>Quantity</th>
    <th>Price Per Unit</th>
    <th>Total Price</th>
    <th>Actions</th>
  </tr>
  <% @inventory_items.each do |inventory_item| %>
    <tr>
      <td><%= inventory_item.item.name %> (<%= inventory_item.item.code %>)</td>
      <td><%= inventory_item.quantity %></td>
      <td><%= inventory_item.item.price %></td>
      <td><%= inventory_item.total %></td>
      <td>
        <%= link_to "Show", inventory_item_path(inventory_item.id) %>
        <%= link_to "Edit", edit_inventory_item_path(inventory_item.id) %>
        <%= link_to "Remove from Shop", inventory_item_path(inventory_item.id), :method => :delete, :data => { :confirm => "Are you sure?" } %>
      </td>
    </tr>
  <% end %>
</table>

app/views/inventory_items/new.html.erb
<% provide(:title, 'New Inventory Item') %>
<h1>New Inventory Item</h1>

<%= simple_form_for(@inventory_item) do |f| %>
  <%= f.association :item %>
  <%= f.input :quantity %>
  <hr>
  <%= f.submit "Save Record" %>
<% end %>

<%= link_to "Back to inventory_items", inventory_items_path %>

app/views/inventory_items/show.html.erb
<% provide(:title, 'Buy Items') %>
<h1>Inventory: <%= @inventory_item.item %></h1>
<h2>Quantity: <%= @inventory_item.quantity %></h2>

<h3>Transactions</h3>
<table>
  <tr>
    <th>Date</th>
    <th>Type</th>
    <th>Quantity</th>
  </tr>
  <% @inventory_item.inventory_transactions.each do |transaction| %>
    <tr>
      <td><%= transaction.transacted_at %></td>
      <td><%= transaction.transaction_type %></td>
      <td><%= transaction.quantity %></td>
    </tr>
  <% end %>
</table>

<%= link_to "Back to Inventory", inventory_items_path %>

app/views/inventory_transactions/index.html.erb
<% provide(:title, 'Transaction History') %>
<h1>Transaction History</h1>

<%= link_to "Shop", inventory_items_path %>
<%= link_to "Item Supplier", items_path %>

<table width="100%">
  <tr>
    <th>Shop Item</th>
    <th>Quantity</th>
    <th>Transaction Date</th>
    <th>Type</th>
  </tr>
  <% @inventory_transactions.each do |inventory_transaction| %>
    <tr>
      <td><%= inventory_transaction.to_x %></td>
      <td><%= inventory_transaction.quantity %></td>
      <td><%= inventory_transaction.transacted_at %></td>
      <td><%= inventory_transaction.transaction_type %></td>
    </tr>
  <% end %>
</table>

app/views/inventory_transactions/new.html.erb
<% provide(:title, 'New Inventory Transaction Item') %>
<h1>New Inventory Transaction Item</h1>

<%= simple_form_for(@inventory_transaction) do |f| %>
  <%= f.association :inventory_item %>
  <%= f.input :transacted_at %>
  <%= f.input :transaction_type, :as => :select, :collection => InventoryTransaction::TRANSACTION_TYPES %>
  <%= f.input :quantity %>
  <hr>
  <%= f.submit "Make Transaction" %>
<% end %>

app/views/items/edit.html.erb
<% provide(:title, 'Edit Item') %>
<h1>Edit Item</h1>

<%= simple_form_for(@item) do |f| %>
  <%= f.input :name %>
  <%= f.input :code %>
  <%= f.input :description %>
  <hr>
  <%= f.submit "Save Record" %>
<% end %>

<%= link_to "Back to items", items_path %>

app/views/items/index.html.erb
<% provide(:title, 'Supply Item') %>
<h1>Item Supplier</h1>
<!-- admins should only see add shop item -->
<%= link_to "Get New Shop Item", new_item_path %>
<!-- users should only see your cart -->
<%= link_to "View Shop", inventory_items_path %>

<table width="100%">
  <tr>
    <th>Name</th>
    <th>Code</th>
    <th> Price</th>
    <th>Actions</th>
  </tr>
  <% @items.each do |item| %>
    <tr>
      <td><%= item.name %></td>
      <td><%= item.code %></td>
      <td><%= item.price %></td>
      <td>
        <%= link_to "Show Item", item_path(item.id) %>
        <!--%= link_to "Edit", edit_item_path(item.id) %-->
        <!-- destroy needs to check if there are carts with that item, otherwise, it screws up the entire cart system -->
        <!--%= link_to "Destroy", item_path(item.id), :method => :delete, :data => { :confirm => "Are you sure?" } %-->
      </td>
    </tr>
  <% end %>
</table>

app/views/items/new.html.erb
<% provide(:title, 'New Item') %>
<h1>New Item</h1>

<%= simple_form_for(@item) do |f| %>
  <%= f.input :name %>
  <%= f.input :code %>
  <%= f.input :description %>
  <%= f.input :price %>
  <hr>
  <%= f.submit "Save Record" %>
<% end %>

<%= link_to "Back to items", items_path %>

app/views/items/show.html.erb
<% provide(:title, 'Show Item') %>
<h1><%= @item.name %></h1>
<p>Item Code: <%= @item.code %></p>
<p>Description: <%= @item.description %></p>
<p>Price: <%= @item.price %></p>

<%= link_to "Back to items", items_path%>

app/views/layouts/_footer.html.erb
<footer class="footer">
	<small>
		<a href="http://railstutorial.org/">Ruby App</a>
		by Bagani Sularte and Miguel Paolo Maglaque
	</small>
	<nav>
		<ul>
		<li><a href="http://io9.com">Geeky Stuff</a></li>
		</ul>
	</nav>
</footer>

app/views/layouts/_header.html.erb
<nav class="navbar navbar-custom navbar-fixed-top">
  <div class="container-fluid">
	<div class="navbar-header">
	  <%= link_to "Shopping Carrot", root_path, id: "logo" %>
	</div>
	<div>
		<ul class="nav navbar-nav">
			<li><%= link_to "Item Supplier", items_path %></li>
			<li><%= link_to "Shop", inventory_items_path %></li>
			<li><%= link_to "Inventory Transactions", inventory_transactions_path %></li>
		</ul>
		<p class="navbar-text pull-right">
		<% if user_signed_in? %>
			Logged in as <strong><%= current_user.email %></strong>.
			<%= link_to 'Edit profile', edit_user_registration_path, :class => 'navbar-link' %> |
			<%= link_to "Logout", destroy_user_session_path, method: :delete, :class => 'navbar-link'  %>
		<% else %>
			<%= link_to "Sign up", new_user_registration_path, :class => 'navbar-link'  %> |
			<%= link_to "Login", new_user_session_path, :class => 'navbar-link'  %>
		<% end %>
	</div>
  </div>
</nav>

app/views/layouts/_shim.html.erb
<!--[if lt IE 9]>
<script src="http://html5shim.googlecode.com/svn/trunk/html5.js"></script>
<![endif]-->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
	<head>
		<title><%= full_title(yield(:title)) %></title>
		<%= stylesheet_link_tag "application", media: "all" %>
		<%= javascript_include_tag "application" %>
		<%= csrf_meta_tags %>
		<%= render 'layouts/shim' %>
	</head>
	<body>
		<style>
			a:hover {
				color: #000;
				background-color: transparent;
				text-decoration: none;
			}
		</style>
		<%= render 'layouts/header' %>
		<div class="container">
			<% if notice %>
			  <p class="alert alert-success"><%= notice %></p>
			<% end %>
			<% if alert %>
			  <p class="alert alert-danger"><%= alert %></p>
			<% end %>
			<%= yield %>
			<%= render 'layouts/footer' %>
		</div>
	</body>
</html>

app/views/pages/index.html.erb
<div class="center hero-unit">
	<h1>The Shopping Carrot</h1>
	
	<h2>
		Where everything is orange...or whatever.
	</h2>
	
	<p>
	</p>
	
	<%= link_to image_tag("orange.png", alt: "Rails"), 'https://www.youtube.com/watch?v=ZN5PoW7_kdA/' %>
</div>